name: yotsuba_schedule_kit_example
description: Demo app for yotsuba_schedule_kit.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  yotsuba_schedule_kit:
    path: ../

flutter:
  uses-material-design: true
